### ISSUE TITLE
Minimal disk initialisation

### ISSUE THREAD

**Issue by szpieg-z-krainy-deszczowcow** [uyjulian/pfsshell#16]
Would You kindly add an option to format drive with only "__mbr" on it? Not all users needs all default partitions (as not all want HDD OSD and/or PSBBN for which they are mandatory). ;) I know that user could delete them later but this could be handy option if user want creating apa scheme on lower space than default 2GiB or in future a vhdd for PS2 emu on PS3.

**Comment by uyjulian** [comment]
I don't have plans to do this myself.  

If someone else sends a pull request adding the option, I will accept it

**Comment by bignaux** [comment]
Even with __mbr only, i don't think we can have small 2GiB , see #23 .

**Comment by bignaux** [comment]
I can provide easy instruction to such need and you could test if it's work if you're still interesting @szpieg-z-krainy-deszczowcow

**Comment by szpieg-z-krainy-deszczowcow** [comment]
@bignaux  I know how to do it by hand, and works fine. But would be nice to have such functionality in PFS Shell (the same as creating all system partitions but all 128MiB, which also works if made by hand). And yes, I can test it if You want. I can even limiting real device size by HPA to simulate such small drive capacity.

**Comment by bignaux** [comment]
In fact my idea, was working on it to automatise test in hdl_dump. I did a 8GB image with pfsshell, using this code : 
https://github.com/bignaux/pfsshell/blob/mkpart/tests/pfsshelltest.tcl
then i use xxd to dump it : 
```
$ time xxd -a test.img test.xxd

real    20m7,453s
user    19m53,414s
sys     0m9,422s
```
due to a bug, it's very long, i'm writing a bug report.
then i finish with a 30kb file (better than a 10mb 7zip file)
for example (here i let some +OPL/directory/pfsshell.md file but you get the idea)
https://gist.githubusercontent.com/bignaux/895e658101e7f26bc3ef1238077661ec/raw/5140a62e292df5d07cd0567ed8179033c2cebb42/test.hex 

* To create custom size disc, you just need to modify the latest address, here we have 0x1fffffff0 for 0x200000000 - 0x10 (8G) 
then : 
` time xxd -r test.hex test.img
`

**Comment by bignaux** [comment]
at least to have only __mbr, you can use hdl_dump initialize test.img MBR.KELF :+1: 

$ fallocate -l 1G test.img
$ hdl_dump initialize test.img MBR.KELF
MBR data successfully injected
$ hdl_dump install test.img ../../hdl-dump/xump.iso
100%

after hdl_dump initialize, the image is full functional in pfsshell : 
# ls
0x0001   128MB __mbr
0x1337   128MB PP.XUMP-00110.HDL.xump
