### ISSUE TITLE
Weird behaviour of initialize command

### ISSUE THREAD

**Issue by bignaux** [uyjulian/pfsshell#23]
On improving the test cover, i found why i can't mkpart or use my test.img with hdl_dump (next candidate for a small CI testing @AKuHAK  ). With 1GB filesize, pfsshell create : 
```
 -0x0100    16MB __system\r
-0x0100    16MB __sysconf\r
-0x0100    16MB __common\r
```
so with 4GB => 64MB, and to have 128MB (normally minimum size according to hdl_dump apa functions) we should have 8GB. Then the file is correct and accept pfsshell mkpart and hdl_dump usage :
```
$ hdl_dump hdl_toc test.img 
type     size flags           dma startup      name
DVD 1200096KB                     TCES_100.01  toremove
total 8192MB, used 1920MB, available 6272MB
```

**Comment by AKuHAK** [comment]
Nice to see that now hdl_dump supports images larger then 2 gb :)

**Comment by bignaux** [comment]
@AKuHAK : image of the hard drive create with fallocate like i did in the last PR. If you are interesting by small testing script like i did on pfsshell, i search some iso we could fetch quickly (like compressed opensource game iso could make less than a MB). Perhaps https://www.retroguru.com/xump/xump-v.latest-ps2.zip

**Comment by uyjulian** [comment]
The default partition size is based on the same behavior as in the libpfs in ps2sdk.

**Comment by bignaux** [comment]
I've found the issue, according to https://ps2linux.no-ip.info/playstation2-linux.com/download/apa/libhdd_ref.pdf : 

`Partition   sizes   are   restricted   to   a   power   of   2   (from 128mb   to   32GB).  However,  the   APA    driver imposes   a   limitation    regarding   the   size   of   a   newly   created    partition.   The   size   is   restricted    to approximately 1/32 the size of the entire hdd, so if for example if the hdd size is 40GB (the size of the official Sony hdd), then the maximum partition size will be 1GB.`

Since using small disk as i do was not intended, i guess the 1/32 size restriction is prior to the 128mb minimal size in the algo in libpfs, that makes 8GB the minimal disk size to have no such issue.

**Comment by Darkshadow2** [comment]
The max partition size is sort of a misnomer. It is a limit, but not like you're thinking.  You can still make a partition of 1GB on that 8GB HDD. It will look like a single partition of 1GB to anyone using it but it's actually a partition and several other sub partitions put together, none of those partitions going above whatever the max partition size has been calculated as.

That's not to say there's not an issue here. It's a bug (of sorts) in the ps2sdk. When it's creating the partitions during initialization, it first creates the `__mbr` partition then it creates the rest in a loop and creates them directly rather than going through the normal partition creation calls. The loop just specifies a start size (of 128MB) and doubles that size through every iteration of the loop. BUT one of the checks it does is see if that size is greater than the max partition size, and if so, drops it to the max partition size. So it never creates sub partitions to make up a partition of the requested size. Interestingly, it only does the doubling / checking after it has created a partition (so it changes the size for the next iteration of the loop). Since it does it that way, the first partition the loop creates will always be at the correct size unless the HDD is less than 256 MB (where it will just fail because it can't create the partition).

@bignaux You didn't put it in your first post, but I'm guessing the `__net` partition was at 128MB, while the rest were at 16MB, right?

I say it's sort of a bug because the official Sony HDD was 40GB so one could say any HDD size below that isn't exactly supported.

The code I'm talking about is in [hdd_fio.c](https://github.com/ps2homebrew/pfsshell/blob/4f7f38af127e7c0f4592eea96b4bd5dc6416249d/subprojects/apa/irx/hdd_fio.c#L316) in pfsshell, or [hdd_fio.c](https://github.com/ps2dev/ps2sdk/blob/11500fe1dcec03592e71406cbd9d34b39aa52589/iop/hdd/apa/src/hdd_fio.c#L322) in ps2sdk - they're exactly the same.

**Comment by bignaux** [comment]
1GB case : 
```
# ls
0x0001   128MB __mbr
0x0100   128MB __net
0x0100    16MB __system
0x0100    16MB __sysconf
0x0100    16MB __common
```
But i don't get it, do you tell that the documentation i quoted is wrong on that limitation of 1/32 of disk size ? I don't have a small disk (less than 8Go) to test on real PS2 if it would work and confirm the error in doc and code.

EDIT: you mean we should have __system with 7 sub-partitions?

**Comment by szpieg-z-krainy-deszczowcow** [comment]
@bignaux The same problem here: https://www.psx-place.com/threads/apa-partition-size-16mib.31327/
And You can limit drive size if You need smaller size. However, not all BIOS and UEFI respecting HPA or DCO (some removing them automatically).

**Comment by AKuHAK** [comment]
There is an official limitation which is listed in `hdd_rule_3.0.2.pdf`. This is the official document, not the one that hiryu wrote  (libhdd_ref.pdf).
According to the Sony specs, the minimal size for any partition or subpartition - is 128Mb.
And yes, it seems that the code for creating default partitions is somehow buggy.
The sizes for the default partitions are constant and due to Sony specs cannot be changed:
```
0x0001   128MB __mbr
0x0100   128MB __net
0x0100   256MB __system
0x0100   512MB __sysconf
0x0100  1024MB __common
```
There is one more limitation - system partitions cannot contain subpartitions.

These 2 limitations lead to such fact the minimal subpartition size is 1024Mb (size of `__common`).
This leads to the limitation that HDD size is greater than `32*minimal subpartition size` is greater than **32Gb**.

That means that if we have an HDD smaller than 32Gb (30Gb for example). Then maximum subpartition size is limited to 512Mb

**Comment by szpieg-z-krainy-deszczowcow** [comment]
> The sizes for the default partitions are constant and due to Sony specs cannot be changed:

@AKuHAK But if user delete all and create his own but in 128MiB in size, everything works fine (in exception of __common in HDD OSD).

**Comment by Darkshadow2** [comment]
Ah, I've never read the official documents, so I didn't know system partitions couldn't have sub partitions. So it makes sense why the code is the way it is.  And like I said, it's really only sort of a bug as HDD size less than 40GB is not entirely supported.  I think the only thing the code could do differently is check if the max partition size is less than 128MB and if so then change it to be 128 rather than the max partition size.  Although I have no idea if the HDD would work correctly if that was done.

**Comment by AKuHAK** [comment]
> Although I have no idea if the HDD would work correctly if that was done.

Exactly, we can try to find one or another solution, but every solution will break compatibility with official tools. Or at least it will need heavy testings, maybe compatibility will not be broken. 1/32 Total HDD size of maximum subpartition is the strongest check, system partition sizes and subpartition not allowing is weaker check. I personally don't know why Sony limited system partitions to not be divided into subpartitions, probably to get rid of potential problems with subpartition handling (when you come from one subpartition to another), maybe to keep it compatible with some old HDD drivers which do not support subpartition, I don't know.
I personally have one 4Gb HDD which works normally with all system partitions splitter into subpartitions. But I didn't test it heavily.


> So it makes sense why the code is the way it is.

The code still should check if HDD is greater than 32Gb, otherwise at least `__common` should be splitted into subpartitions.

**Comment by AKuHAK** [comment]
PS3 BC has somehow broken this compatibility. Their HDD images (which are in fact just PS2 HDD images with APA structure) are less than 40 Gb. One image is 8Gb, another is about 21Gb. They did it by faking HDD size (all utilities will report that HDD is 40Gb). To prevent programs to write over that limit, they created fake partition which fills the rest of the disk, and made this partition system (started from __ ) so normal apps cannot touch it.

**Comment by bignaux** [comment]
I reopened the issue since i think it's a bug, or at least we can improve and continue discussion and test. I find really interesting to provide regression test on CI, and 8Go is still big, i can't afford 40Gb to be in the Sony shoes. More important than the official documentation, is the real behavior on console. @szpieg-z-krainy-deszczowcow claims "everything works fine..." so let us dig that a bit. Faked partition, i note.

**Comment by AKuHAK** [comment]
Fixed in https://github.com/ps2homebrew/pfsshell/pull/29
