### ISSUE TITLE
[ISSUE]: Cannot create a partition larger than 4096gb

### ISSUE THREAD

**Issue by GDX-X** [uyjulian/pfsshell#30]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

Hello I can not create a partition of more than 4096gb or more I have tried several versions of pfsshell the problem persists

![c7c07b3a4d64bc6b38a3f1b8701e6fa7](https://user-images.githubusercontent.com/22562949/141222768-ab6ea6e4-41fa-477c-acbf-bb9c7eeb48d4.png)

### Console model

SCPH-39004

**Comment by AKuHAK** [comment]
@GDX-X could you confirm that this bug also persists in the [beta version](https://github.com/ps2homebrew/pfsshell/releases/tag/latest)?

**Comment by GDX-X** [comment]
@AKuHAK Yes I still confirm present in the beta version

**Comment by GDX-X** [comment]
If you want more info when I create the 128gb __.POPS partition on wLaunchELF. pfsshell will see it in increments of 4096M
![915a377b4bdb08356737bf9ad3464190](https://user-images.githubusercontent.com/22562949/147858464-c9a21ebd-a16b-4414-b3de-e6555c3069dc.png)
B

**Comment by AKuHAK** [comment]
Mmm I dont see any bug here... Could you tell me what is the problem? The screen looks valid.

**Comment by AKuHAK** [comment]
Also could you run ls -l command

**Comment by uyjulian** [comment]
I believe this is the correct behavior. PFS does not support partitions larger than a certain size.

**Comment by AKuHAK** [comment]
@GDX-X also looks like you qre not using the dev build of pfsshell. `ls -l` command will work only in the latest build.

**Comment by AKuHAK** [comment]
@GDX-X 

1. You are not using the latest version of pfsshell
2. This is expected behaviour

Look:
```
# ls -l
0x0001     128MB  2018-08-04 03:29  __mbr
0x0100     128MB  2001-10-21 00:24  __net/
0x0100     256MB  2018-08-04 03:29  __system/
0x0100     512MB  2018-08-04 03:29  __sysconf/
0x0100    1024MB  2018-08-04 03:29  __common/
0x0100    1024MB  2018-08-04 17:04  PP.SLPS-20200.1000.POLVIEWER/
0x0100    1024MB  2018-08-06 21:40  PP.SCUS-97269.1000.POLVIEWER/
0x0100    1024MB  2019-03-31 17:06  __contents/
0x0100    1024MB  2019-03-31 17:08  __linux.9/
0x0100    1024MB  2019-03-31 17:08  __linux.9@
0x0088     512MB  2018-11-14 23:34  __linux.4
0x0088     512MB  2018-11-14 23:36  __linux.5
0x0088     128MB  2018-11-14 23:36  __linux.6
0x0082     128MB  2018-11-14 23:39  __linux.2
0x0088     256MB  2018-11-14 23:40  __linux.7
0x0083     512MB  2013-10-24 02:08  __linux.10
0x0083    1024MB  2013-10-31 01:20  __linux.1
0x0083    1024MB  2013-10-31 01:20  __linux.1@
0x0100     256MB  2013-11-01 01:48  PP.POPS/
0x0100     128MB  2012-12-22 23:33  PP.ULE/
0x0100     128MB  2019-03-31 18:38  PP.OPL/
0x0000     512MB  2019-03-16 21:12  __empty%
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO/
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
0x0100    1024MB  2019-03-16 21:12  PP.SLPM-65981.0004.FMO@
```
If you see `/ `symbol at the end - this means that this is the main partition of type PFS.
If you see `@`symbol at the end - this means that this is the sub-partition of any type.
If you see `%`symbol at the end - this means that this is an empty partition (free space).

Any partition should contain one main partition and many sub-partitions - this is how the APA partition scheme works.

`pfsshell` shows the low-level structure, it doesn't have an option to show high-level structure (showing only main partition metadata and calculating partition size by summing all main partitions and subpartitions together as wlaucnhELF does). You should understand that both options are valid, pfsshell uses more low-level options.
